name = "Mabuya"
description = "🦎 A minimal Zola theme for building light and SEO-ready blogs."
license = "MIT"
homepage = "https://github.com/semanticdata/mabuya"
min_version = "0.18.0"
demo = "https://mabuya.vercel.app/"

[author]
name = "Miguel Pimentel"
homepage = "https://miguelpimentel.do/"

[original]
author = "Chester How"
homepage = "https://chester.how/"
repo = "https://github.com/chesterhow/tale"
